services:
  - type: web
    name: scratch-starter-project
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    routes:
      - type: static
        source: /static
        destination: /static
      - type: static
        source: /assets
        destination: /assets
      - type: static
        source: /
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 16.x
      - key: NODE_ENV
        value: production